### PR TITLE
Add fuse-t support

### PR DESCRIPTION
**Pull request by macos-fuse-t**
Very basic support, currently without any mount options
But loopbackfs seems to be working

### CODE REVIEW

**Comment by anacrolix** [comment]
There were some issues with the PR, it must have been very old code. I've cleaned it up and got it building and working for anacrolix/torrent on master. Some of the unit tests fail on Mac M1 but I don't know if they ever worked.

**Comment by alexfs** [comment]
Let me know how to run the tests and I will take a look

**Comment by anacrolix** [comment]
go test ./...

**Comment by macos-fuse-t** [comment]
The testing code itself seems to be broken, it hangs because of concurrency issues. When running tests one by one I managed to fix most of them. Will send a PR soon.

**Comment by anacrolix** [comment]
Thanks. Yeah that was the behaviour I was seeing too. I look forward to your PR!

**Pull request merged**
